### ISSUE TITLE
如何查看数据库

### ISSUE THREAD

**Issue by Aiooon** [twtrubiks/django-tutorial#1]
在这个项目中  我执行到这一步时：
![6d7cf121 409e2a6c30 aa5bf159 jpg_recompress](https://user-images.githubusercontent.com/32924855/32037226-e0742b08-ba56-11e7-8ff4-e945c33133e5.jpg)

我无法找到和链接到我所建的数据库和表
![1 jpg](https://user-images.githubusercontent.com/32924855/32037505-27fd2848-ba58-11e7-9a72-ab4fce29fa03.jpg)

![826b9e4c 40ebef0520 aa5bf159 jpg_recompress](https://user-images.githubusercontent.com/32924855/32037518-37a9d0ac-ba58-11e7-8f72-12e34c71f3d3.jpg)

起初我以为是表创建失败了，但是在我执行后面的步骤时，发现可以对数据库进行正常操作，但我仍然无法找到我的数据库和表，pycharm中也没有显示
![616c88a12d9446ea90cb7d47a242ead2](https://user-images.githubusercontent.com/32924855/32037534-498cd7ce-ba58-11e7-8dac-0b8cd664c2bd.jpg)
![d6baac89 404754b179 aa5bf159 jpg_recompress](https://user-images.githubusercontent.com/32924855/32037541-4fd4e87e-ba58-11e7-8eba-d469387a902f.jpg)

查了很多方法还是没有解决，希望你能帮助我，谢谢！

**Comment by twtrubiks** [comment]
hi @Aiooon 
我從你的截圖看，db.sqlite3在你的路徑 django-tutorial/db.sqlite3 

1.使用pycharm查看資料庫
你沒辦法從 pycharm 看db，應該只是因為你沒有 driver (download missing driver files)
安裝完後（點你截圖上的 download ），應該就可以使用了。

2.使用 [sqlitebrowser](http://sqlitebrowser.org/) 觀看資料庫
下載後，將你的 db.sqlite3 用 sqlitebrowser 開啟即可。

**Comment by Aiooon** [comment]
非常感谢！已经解决了！

**Comment by ekils** [comment]
請問，superuser 創建後能否刪除？以及如何修改superuser的密碼？

**Comment by twtrubiks** [comment]
@ekils 當然可以刪除。

修改superuser的密碼
```cmd
python manage.py changepassword *username* 
```
官方文件 [Changing passwords](https://docs.djangoproject.com/en/2.0/topics/auth/default/#changing-passwords)
